""" Tests to demonstrate how to repeat the same test multiple times.
    The 1st example uses the "parameterized" library.
    The 2nd example uses "pytest.mark.parametrize()". (NO class)
    The 3rd example uses "pytest.mark.parametrize()". (in class) """

import pytest
from parameterized import parameterized
from seleniumbase import BaseCase


class RepeatTests(BaseCase):
    @parameterized.expand([[]] * 10000)
    def test_repeat_this_test_with_parameterized(self):
        self.open("https://google.com/ncr")
        self.highlight('input[name="q"]', loops=3)
        self.type('input[name="q"]', "hermanherry")
        self.sleep(1)
        self.highlight("div.sbic", loops=2, scroll=False)
        self.sleep(10)
        self.click_if_visible("div.sbic")
        self.sleep(5)
        self.execute_script("window.scrollBy(0, 2878)")
        self.highlight("div.GNJvt", loops=2, scroll=False)
        self.click_if_visible("div.GNJvt")
        self.execute_script("window.scrollBy(0, 2998)")
        self.sleep(10)
        self.highlight('a[href*="https://hermanherry.id/"]', loops=3)
        self.click('a[href*="https://hermanherry.id/"]')
        self.sleep(10)
        self.highlight("#aswift_2_expand", loops=4, scroll=True)
        self.click_if_visible('#aswift_2_expand')
        self.execute_script("window.scrollBy(0, 988)")
        self.sleep(10)
        self.open("https://google.com/ncr")
        self.highlight('input[name="q"]', loops=3)
        self.type('input[name="q"]', "hermanherry")
        self.sleep(1)
        self.highlight("div.sbic", loops=2, scroll=False)
        self.sleep(10)
        self.click_if_visible("div.sbic")
        self.sleep(5)
        self.execute_script("window.scrollBy(0, 2878)")
        self.highlight("div.GNJvt", loops=2, scroll=False)
        self.click_if_visible("div.GNJvt")
        self.execute_script("window.scrollBy(0, 2998)")
        self.sleep(10)
        self.highlight('a[href*="https://hermanherry.id/"]', loops=3)
        self.click('a[href*="https://hermanherry.id/"]')
        self.sleep(10)
        self.highlight("#aswift_3_expand", loops=4, scroll=True)
        self.click_if_visible('#aswift_3_expand')
        self.execute_script("window.scrollBy(0, 988)")
        self.sleep(10)
        self.open("https://google.com/ncr")
        self.highlight('input[name="q"]', loops=3)
        self.type('input[name="q"]', "hermanherry")
        self.sleep(1)
        self.highlight("div.sbic", loops=2, scroll=False)
        self.sleep(10)
        self.click_if_visible("div.sbic")
        self.sleep(5)
        self.execute_script("window.scrollBy(0, 2878)")
        self.highlight("div.GNJvt", loops=2, scroll=False)
        self.click_if_visible("div.GNJvt")
        self.execute_script("window.scrollBy(0, 2998)")
        self.sleep(10)
        self.highlight('a[href*="https://hermanherry.id/"]', loops=3)
        self.click('a[href*="https://hermanherry.id/"]')
        self.sleep(10)
        self.highlight("#aswift_4_expand", loops=4, scroll=True)
        self.click_if_visible('#aswift_4_expand')
        self.execute_script("window.scrollBy(0, 988)")
        self.sleep(10)
        self.open("https://google.com/ncr")
        self.highlight('input[name="q"]', loops=3)
        self.type('input[name="q"]', "hermanherry")
        self.sleep(1)
        self.highlight("div.sbic", loops=2, scroll=False)
        self.sleep(10)
        self.click_if_visible("div.sbic")
        self.sleep(5)
        self.execute_script("window.scrollBy(0, 2878)")
        self.highlight("div.GNJvt", loops=2, scroll=False)
        self.click_if_visible("div.GNJvt")
        self.execute_script("window.scrollBy(0, 2998)")
        self.sleep(10)
        self.highlight('a[href*="https://hermanherry.id/"]', loops=3)
        self.click('a[href*="https://hermanherry.id/"]')
        self.sleep(10)
        self.highlight("#aswift_1_expand", loops=4, scroll=True)
        self.click_if_visible('#aswift_1_expand')
        self.execute_script("window.scrollBy(0, 988)")
        self.sleep(10)
        self.open("https://google.com/ncr")
        self.highlight('input[name="q"]', loops=3)
        self.type('input[name="q"]', "hermanherry")
        self.sleep(1)
        self.highlight("div.sbic", loops=2, scroll=False)
        self.sleep(10)
        self.click_if_visible("div.sbic")
        self.sleep(5)
        self.execute_script("window.scrollBy(0, 2878)")
        self.highlight("div.GNJvt", loops=2, scroll=False)
        self.click_if_visible("div.GNJvt")
        self.execute_script("window.scrollBy(0, 2998)")
        self.sleep(10)
        self.highlight('a[href*="https://hermanherry.id/"]', loops=3)
        self.click('a[href*="https://hermanherry.id/"]')
        self.sleep(10)
        self.highlight("#aswift_1_expand", loops=4, scroll=True)
        self.click_if_visible('#aswift_1_expand')
